# Logging & Error Handling

## Базовая реализация

1. Логирование (как минимум `url`, `query parameters`, `body`) для всех запросов к серверу, а также кода ответа (`status code`)**плюс 20 баллов**
2. Добавлена централизованная обработка всех ошибок, которая включает отправку респонса с соответствующим кодом http статуса и их логирование **плюс 20 баллов**
3. Добавлены обработка и логирование ошибок на событие `uncaughtException` **плюс 10 баллов**
4. Добавлены обработка и логирование ошибок на событие `unhandledRejection` **плюс 10 баллов**
5. Процесс логирования осуществляется единственным модулем (т.е. код, осуществляющий логирование, находится в одном модуле, при этом этот модуль может **использоваться** внутри других модулей) **плюс 20 баллов**

## Продвинутая реализация
1. Логи записываются в файл **плюс 20 баллов**
2. Логи ошибок записываются в отдельный файл (либо только в него, либо в дополнение к записи в общий файл) **плюс 10 баллов**

## Штрафы
* Наличие изменений в тестах либо в workflow **минус 100 баллов**
* Внесение изменений в репозиторий после дедлайна не считая коммиты, вносящие изменения только в `Readme.md` и вспомогательные файлы **минус 30% от максимального балла за задание (для этого задания 33 балла)**
* За каждый непрошедший тест **минус 10 баллов**
* За **каждую** ошибку линтера при запуске `npm run lint` на основе **локального конфига**, равно как и за ошибки компиляции на основе локального tsconfig **минус 10 баллов** (именно `errors`, не `warnings`)
* Имеется явно указанный тип `any` **минус 20 баллов** за каждое использование
* За отсутствие отдельной ветки для разработки **минус 20 баллов**
* За отсутствие `Pull Request` **минус 20 баллов**
* За неполную информацию в описании `Pull Request` (отсутствует либо некорректен один из 3 обязательных пунктов) **минус 20 баллов**
* Меньше 3 коммитов в ветке разработки, не считая коммиты, вносящие изменения только в `Readme.md`, либо другие вспомогательные файлы — **минус 20 баллов**

**Подсказки:**
- _(3 пункт)_ Для проверки пропишите `throw Error('Oops!')` ПОСЛЕ `process.on('uncaughtException', () => {...})`. Например, в случае с Express:
```ts
// Express initialization
const app = express().use(...);

// Exceptions catcher
process.on('uncaughtException'...);

// PUT IT HERE
throw Error('Oops!');

module.exports = app;
```
_Как результат_: вывод в консоли отловленной ошибки

- _(4 пункт)_ Для проверки пропишите `Promise.reject(Error('Oops!'))` ВНЕ инициализации express и ПОСЛЕ `process.on('unhandledRejection', () => {...})`. Например, в случае с Express:
```ts
// Express initialization
const app = express().use(...);

// Exceptions catcher
process.on('unhandledRejection'...);

// PUT IT HERE
Promise.reject(Error('Oops!'));

module.exports = app;
```
_Как результат_: вывод в консоли отловленной ошибки
